version: '3.8'
services:
  postgres:
    image: postgres:15.4-alpine
    container_name: brc20_indexer_stacks_pg
    command: postgres -c 'max_connections=1000'
    profiles: ['dev', 'ci']
    shm_size: 1gb
    ports:
      - '19432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4xQUdohS4oIn8pKW
      POSTGRES_DB: stacks_blockchain_api
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  stacks-blockchain-api:
    image: bestmike007/stacks-blockchain-api:7.3.0
    container_name: brc20_indexer_stacks_api
    profiles: ['dev', 'ci']
    command: sh -c "/wait && node ./lib/index.js"
    ports:
      - '19999:3999'
    environment:
      WAIT_HOSTS: 'postgres:5432'
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: 4xQUdohS4oIn8pKW
      PG_DATABASE: stacks_blockchain_api
      PG_SCHEMA: stacks_blockchain_api
      STACKS_CORE_EVENT_PORT: '3700'
      STACKS_CORE_EVENT_HOST: http://0.0.0.0
      STACKS_BLOCKCHAIN_API_PORT: '3999'
      STACKS_BLOCKCHAIN_API_HOST: 0.0.0.0
      STACKS_CORE_RPC_HOST: stacks-blockchain
      STACKS_CORE_RPC_PORT: '20443'
      STACKS_CHAIN_ID: '0x80000000'
      NODE_ENV: development
      STACKS_API_ENABLE_FT_METADATA: 1
      STACKS_API_ENABLE_NFT_METADATA: 1
    volumes:
      - $PWD/wait:/wait
  stacks-blockchain:
    image: bestmike007/stacks-blockchain:alex-v20230808
    container_name: brc20_indexer_stacks_node
    profiles: ['dev', 'ci']
    command: sh -c "/wait && stacks-node start --config=/app/config/Stacks.toml"
    ports:
      - '19443:20443'
      - '19445:20445'
    environment:
      WAIT_BEFORE: 3
      WAIT_AFTER: 3
      WAIT_HOSTS: 'stacks-blockchain-api:3700'
      NOP_BLOCKSTACK_DEBUG: 1
      XBLOCKSTACK_DEBUG: 1
      RUST_BACKTRACE: 1
      STACKS_CHAIN_ID: '0x80000000'
      V2_POX_MIN_AMOUNT_USTX: 90000000260
      STACKS_CORE_RPC_HOST: stacks-blockchain
      STACKS_CORE_RPC_PORT: 20443
      STACKS_API_ENABLE_FT_METADATA: 1
      STACKS_API_ENABLE_NFT_METADATA: 1
      STACKS_NODE_PUPPET_MODE: 'true'
    volumes:
      - stacks_blockchain_chaindata:/root/stacks-node/data
      - $PWD/stacks-blockchain/config:/app/config
      - $PWD/wait:/wait
  stacks-blockchain-explorer:
    image: hirosystems/explorer:1.39.0
    container_name: brc20_indexer_stacks_explorer
    profiles: ['dev']
    ports:
      - '19000:3000'
    extra_hosts:
      - 'gateway.docker.internal:host-gateway'
    environment:
      MAINNET_API_SERVER: http://gateway.docker.internal:18999
      NEXT_PUBLIC_MAINNET_API_SERVER: ${PUBLIC_MAINNET_API_SERVER:-http://gateway.docker.internal:18999}
      NEXT_PUBLIC_MAINNET_ENABLED: 'true'
      NODE_ENV: development
volumes:
  pgdata: {}
  stacks_blockchain_chaindata: {}
