[project]
name = 'brc20-indexer-v1'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[repl]
costs_version = 2

# [repl.analysis]
# passes = ['check_checker']

# [repl.analysis.check_checker]
# strict = false
# trusted_sender = false
# trusted_caller = false
# callee_filter = false

[contracts.clarity-bitcoin]
path = 'contracts/clarity-bitcoin.clar'
clarity_version = 2
epoch = 2.1

# [contracts.btc-bridge-endpoint]
# path = 'contracts/btc-bridge-endpoint.clar'

# [contracts.token-abtc]
# path = 'contracts/token-abtc.clar'

