[project]
name = 'brc20-indexer-v1'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[repl]
costs_version = 2

# [repl.analysis]
# passes = ['check_checker']

# [repl.analysis.check_checker]
# strict = false
# trusted_sender = false
# trusted_caller = false
# callee_filter = false

[contracts.clarity-bitcoin]
path = 'contracts/clarity-bitcoin.clar'
clarity_version = 2
epoch = 2.1

[contracts.utils]
path = 'contracts/utils.clar'
clarity_version = 2
epoch = 2.1

[contracts.indexer]
path = 'contracts/indexer.clar'
clarity_version = 2
epoch = 2.1
depends_on = ["clarity-bitcoin", "indexer-registry"]

[contracts.indexer-registry]
path = 'contracts/indexer-registry.clar'
clarity_version = 2
epoch = 2.1
depends_on = ["clarity-bitcoin"]
