name: CI Clarinet

# Controls when the action will run.
on:
  push:

concurrency:
  group: 'ci-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  check:
    name: check - ${{ github.ref_name }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      # - uses: sergeysova/jq-action@v2
      # - uses: wei/curl@v1
      # - name: Install Deps
      #   run: |
      #     ./scripts/clarinet_manager.sh install
      - name: "Check contract"
        uses: docker://hirosystems/clarinet:1.5.4
        with:
          entrypoint: "bash"
          args: -c "clarinet check"
  test:
    name: test - ${{ github.ref_name }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      # - uses: sergeysova/jq-action@v2
      # - uses: wei/curl@v1
      # - name: Install Deps
      #   run: |
      #     ./scripts/clarinet_manager.sh install
      - name: "Execute test suite"
        uses: docker://hirosystems/clarinet:1.5.4
        with:
          entrypoint: "bash"
          args: -c "clarinet test"
